### Read all users
GET http://localhost:3002/users

### Create test a new user
POST http://localhost:3002/users
Content-Type: application/json

{
"username": "Susan",
"email": "susan@example.com",
"passwrod": "456789123"
}

### Update user
PUT http://localhost:3002/users/1
Content-Type: application/json

{
"username": "Emmika",
"email": "Emmika@gmail.com",
"passwrod": "Em12345"
}