### Read all users 
GET http://localhost:3002/api/V2/users

### Create a new uer
POST http://localhost:3002/api/V2/users
Content-Type:  application/json

{
    "username": "Charlie",
    "email": "charliebrfbo@something.com",
    "password":"pass1234"

}

### Create user - David
POST http://localhost:3002/api/V2/users
Content-Type: application/json

{
    "username": "David",
    "email": "david@example.com",
    "password": "pass5678"
}

### Create user - Emma
POST http://localhost:3002/api/V2/users
Content-Type: application/json

{
    "username": "Emma",
    "email": "emma@example.com",
    "password": "pass9012"
}